<ul class="social-profiles element" data-visibility="<?php echo esc_attr(isset($element['visibility']) ? $element['visibility'] : 'desktop'); ?>">
    <?php if(get_theme_mod('nucleus_facebook_profile')) : ?><li class="facebook"><a href="<?php echo esc_url(get_theme_mod('nucleus_facebook_profile')); ?>" target="_blank"><i class="fa fa-facebook"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_twitter_profile')) : ?><li class="twitter"><a href="<?php echo esc_url(get_theme_mod('nucleus_twitter_profile')); ?>" target="_blank"><i class="fa fa-twitter"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_dribbble_profile')) : ?><li class="dribbble"><a href="<?php echo esc_url(get_theme_mod('nucleus_dribbble_profile')); ?>" target="_blank"><i class="fa fa-dribbble"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_deviantart_profile')) : ?><li class="deviantart"><a href="<?php echo esc_url(get_theme_mod('nucleus_deviantart_profile')); ?>" target="_blank"><i class="fa fa-deviantart"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_instagram_profile')) : ?><li class="instagram"><a href="<?php echo esc_url(get_theme_mod('nucleus_instagram_profile')); ?>" target="_blank"><i class="fa fa-instagram"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_pinterest_profile')) : ?><li class="pinterest"><a href="<?php echo esc_url(get_theme_mod('nucleus_pinterest_profile')); ?>" target="_blank"><i class="fa fa-pinterest"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_bloglovin_profile')) : ?><li class="bloglovin"><a href="<?php echo esc_url(get_theme_mod('nucleus_bloglovin_profile')); ?>" target="_blank"><i class="fa fa-heart"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_google_plus_profile')) : ?><li class="google-plus"><a href="<?php echo esc_url(get_theme_mod('nucleus_google_profile')); ?>" target="_blank"><i class="fa fa-google-plus"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_tumblr_profile')) : ?><li class="tumblr"><a href="<?php echo esc_url(get_theme_mod('nucleus_tumblr_profile')); ?>" target="_blank"><i class="fa fa-tumblr"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_youtube_profile')) : ?><li class="youtube"><a href="<?php echo esc_url(get_theme_mod('nucleus_youtube_profile')); ?>" target="_blank"><i class="fa fa-youtube"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_vimeo_profile')) : ?><li class="vimeo"><a href="<?php echo esc_url(get_theme_mod('nucleus_vimeo_profile')); ?>" target="_blank"><i class="fa fa-vimeo"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_sound_cloud_profile')) : ?><li class="sound-cloud"><a href="<?php echo esc_url(get_theme_mod('nucleus_sound_cloud_profile')); ?>" target="_blank"><i class="fa fa-soundcloud"></i></a></li><?php endif; ?>
    <?php if(get_theme_mod('nucleus_rss_url')) : ?><li class="rss"><a href="<?php echo esc_url(get_theme_mod('nucleus_rss_url')); ?>" target="_blank"><i class="fa fa-rss"></i></a></li><?php endif; ?>
</ul>
